apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  template:
    metadata:
      labels:
       name: aplicacao-pod
    spec:
      containers:
        - name: container-aplicacao-loja
          image: rafanercessian/aplicacao-loja:v1 #ACR: <nomeregistry.azurecr.io>/<pasta>/<nome-imagem>:vers√£o
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: aplicacao-pod
